name: Tests

on:
  push:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']
    branches:
    - 'master'
    - 'release/*'
  pull_request:
    paths-ignore: ['*.md', 'CODEOWNERS', 'LICENSE']

jobs:
  # Runs the pom sorter and code formatter to ensure that the code
  # is formatted and poms are sorted according to project rules. This
  # will fail if the formatter makes any changes.
  check-code-formatting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'zulu'
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-format-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-format-
          ${{ runner.os }}-maven-
    - name: Format code
      run: |
        mvn -V -B -e -ntp "-Dstyle.color=always" clean formatter:format sortpom:sort -Pautoformat
        git status
        git diff-index --quiet HEAD || (echo "Error! There are modified files after formatting." && false)
      env:
        MAVEN_OPTS: "-Djansi.force=true -Dhttps.protocols=TLSv1.2 -Djava.awt.headless=true"
        GITHUB_TOKEN: ${{ github.token }}
